name: chat_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.3
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  dio: ^4.0.4
  video_player: ^2.2.18
  cached_network_image: ^3.2.1
  audio_video_progress_bar: ^0.10.0
  agora_rtc_engine: ^5.2.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.6
  onesignal_flutter: ^3.3.0
  firebase_messaging: ^11.2.6
  audioplayers: ^0.20.1
  record: ^3.0.2
  pinput: ^2.2.11
  permission_handler: ^9.0.1
  flutter_local_notifications: ^9.4.0
  image_picker: ^0.8.4+6
  firebase_database: ^9.0.6
  external_path: ^1.0.1
  enx_flutter_plugin: ^2.1.2
  assets_audio_player: ^3.0.5
  awesome_notifications: ^0.6.21
  sqflite: ^2.0.3+1
  media_info: ^0.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/audios/
    - assets/fonts/
  fonts:
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
    - family: RobotoBlackItalic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    - family: RobotoBoldItalic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
    - family: RobotoItalic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
    - family: RobotoLightItalic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
    - family: RobotoMediumItalic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
    - family: RobotoThinItalic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf

    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
    - family: OpenSansBoldItalic
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
    - family: OpenSansExtraBold
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
    - family: OpenSansExtraBoldItalic
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
    - family: OpenSansItalic
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
    - family: OpenSansLight
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
    - family: OpenSansLightItalic
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
    - family: OpenSansSemiBold
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
    - family: OpenSansSemiBoldItalic
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf

